[[CURRENCIES]]
code="AMT"
issuer="GAVFYNEHSTW4P65DM75P4TYAC6PNO5A6LGSYSGEFNN3O7A23XHWABSBP"
name="Alberto Marketplace Token"
desc="AMT is a Pi Testnet utility token for the Alberto Marketplace and Junakis: Rise of the Legends development ecosystem. Testnet only; no Mainnet value."
image="https://bonene28.github.io/amt.png"